# Use postgres/password user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: jmticonap/reservas-api
    restart: always
    ports:
      - 8000:8000
    network_mode: "host"
